crud.boton.crear=Guardar
crud.boton.actualizar=Actualizar
crud.boton.eliminar=Eliminar
crud.boton.cancelar=Cancelar
confirm.eliminar.header=Confirmaci\u00f3n
confirm.eliminar.mensaje=\u00bfEst\u00e1s seguro de eliminar este registro?
menu.opciones=Opciones
menu.inicio=Inicio
menu.idioma=Idioma
menu.iniciar_sesion=Iniciar sesi\u00f3n